// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calls.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const ackCall = `-- name: AckCall :exec
update calls
set status = 'ack', acked_at = now()
where id = $1 and status = 'new'
`

// Acknowledge a call (new → ack). No-op if it is not currently new.
func (q *Queries) AckCall(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, ackCall, id)
	return err
}

const createCall = `-- name: CreateCall :one
insert into calls (restaurant_id, table_id, type)
values ($1, $2, $3)
returning id, restaurant_id, table_id, type, status, created_at, acked_at, done_at
`

type CreateCallParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	TableID      string    `json:"table_id"`
	Type         string    `json:"type"`
}

// Guest taps "Позвать" at their table → a new call lands in /admin/calls.
func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) (Call, error) {
	row := q.db.QueryRow(ctx, createCall, arg.RestaurantID, arg.TableID, arg.Type)
	var i Call
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.AckedAt,
		&i.DoneAt,
	)
	return i, err
}

const doneCall = `-- name: DoneCall :exec
update calls
set status = 'done',
    done_at = now(),
    acked_at = coalesce(acked_at, now())
where id = $1 and status <> 'done'
`

// Complete a call; backfill acked_at if it was never acknowledged.
func (q *Queries) DoneCall(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, doneCall, id)
	return err
}

const listActiveCalls = `-- name: ListActiveCalls :many
select id, restaurant_id, table_id, type, status, created_at, acked_at, done_at from calls
where restaurant_id = $1 and status in ('new', 'ack')
order by case status when 'new' then 0 when 'ack' then 1 else 2 end,
         created_at desc
`

// Active calls: new before ack, freshest first within each group.
func (q *Queries) ListActiveCalls(ctx context.Context, restaurantID uuid.UUID) ([]Call, error) {
	rows, err := q.db.Query(ctx, listActiveCalls, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.TableID,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.AckedAt,
			&i.DoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveCalls = `-- name: ListArchiveCalls :many
select id, restaurant_id, table_id, type, status, created_at, acked_at, done_at from calls
where restaurant_id = $1 and status = 'done'
order by coalesce(done_at, created_at) desc
`

// Completed calls, most recently done first.
func (q *Queries) ListArchiveCalls(ctx context.Context, restaurantID uuid.UUID) ([]Call, error) {
	rows, err := q.db.Query(ctx, listArchiveCalls, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Call{}
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.TableID,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.AckedAt,
			&i.DoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
