// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: components.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listComponentsByRecipeID = `-- name: ListComponentsByRecipeID :many
select id, recipe_id, brand, flavour, percent, created_at from components
where recipe_id = $1
order by created_at
`

func (q *Queries) ListComponentsByRecipeID(ctx context.Context, recipeID uuid.UUID) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponentsByRecipeID, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Brand,
			&i.Flavour,
			&i.Percent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
