// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteDevice = `-- name: DeleteDevice :exec
delete from devices where fcm_token = $1
`

// Drop a device token (logout / FCM reports it unregistered).
func (q *Queries) DeleteDevice(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deleteDevice, fcmToken)
	return err
}

const listOnShiftDeviceTokens = `-- name: ListOnShiftDeviceTokens :many
select distinct d.fcm_token
from devices d
join shifts s
  on s.employee_id   = d.employee_id
 and s.restaurant_id = d.restaurant_id
 and s.shift_date    = current_date
where d.restaurant_id = $1
`

// FCM tokens of staff who are on today's shift at this venue — the push audience.
func (q *Queries) ListOnShiftDeviceTokens(ctx context.Context, restaurantID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOnShiftDeviceTokens, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var fcm_token string
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDevice = `-- name: RegisterDevice :one
insert into devices (employee_id, restaurant_id, platform, fcm_token)
values ($1, $2, $3, $4)
on conflict (fcm_token) do update
set employee_id   = excluded.employee_id,
    restaurant_id = excluded.restaurant_id,
    platform      = excluded.platform,
    updated_at    = now()
returning id, employee_id, restaurant_id, platform, fcm_token, created_at, updated_at
`

type RegisterDeviceParams struct {
	EmployeeID   uuid.UUID `json:"employee_id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Platform     string    `json:"platform"`
	FcmToken     string    `json:"fcm_token"`
}

// Upsert a staff device's FCM token (idempotent by token; re-binds to the latest
// employee/restaurant on re-login or device hand-off).
func (q *Queries) RegisterDevice(ctx context.Context, arg RegisterDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, registerDevice,
		arg.EmployeeID,
		arg.RestaurantID,
		arg.Platform,
		arg.FcmToken,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.RestaurantID,
		&i.Platform,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
