// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmployee = `-- name: CreateEmployee :one
insert into employees (first_name, last_name, middle_name, short_name)
values ($1, $2, $3, $4)
returning id, first_name, last_name, middle_name, short_name, created_at, updated_at
`

type CreateEmployeeParams struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	MiddleName string `json:"middle_name"`
	ShortName  string `json:"short_name"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.ShortName,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.ShortName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRestaurant = `-- name: CreateRestaurant :one
insert into restaurants (name, code)
values ($1, $2)
returning id, name, code, created_at, updated_at
`

type CreateRestaurantParams struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, createRestaurant, arg.Name, arg.Code)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeesByIDs = `-- name: GetEmployeesByIDs :many
select id, first_name, last_name, middle_name, short_name, created_at, updated_at from employees
where id = any($1::uuid[])
`

func (q *Queries) GetEmployeesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, getEmployeesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.ShortName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRestaurantByCode = `-- name: GetRestaurantByCode :one
select id, name, code, created_at, updated_at from restaurants
where code = $1
`

func (q *Queries) GetRestaurantByCode(ctx context.Context, code string) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantByCode, code)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkEmployeeRestaurant = `-- name: LinkEmployeeRestaurant :exec
insert into employee_restaurants (employee_id, restaurant_id, position)
values ($1, $2, $3)
on conflict (employee_id, restaurant_id)
do update set position = coalesce(excluded.position, employee_restaurants.position)
`

type LinkEmployeeRestaurantParams struct {
	EmployeeID   uuid.UUID `json:"employee_id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Position     *string   `json:"position"`
}

func (q *Queries) LinkEmployeeRestaurant(ctx context.Context, arg LinkEmployeeRestaurantParams) error {
	_, err := q.db.Exec(ctx, linkEmployeeRestaurant, arg.EmployeeID, arg.RestaurantID, arg.Position)
	return err
}

const listEmployeesByRestaurant = `-- name: ListEmployeesByRestaurant :many
select e.id, e.first_name, e.last_name, e.middle_name, e.short_name, e.created_at, e.updated_at, er.position
from employees e
join employee_restaurants er on er.employee_id = e.id
where er.restaurant_id = $1
order by e.last_name, e.first_name
`

type ListEmployeesByRestaurantRow struct {
	ID         uuid.UUID `json:"id"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	MiddleName string    `json:"middle_name"`
	ShortName  string    `json:"short_name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Position   *string   `json:"position"`
}

func (q *Queries) ListEmployeesByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]ListEmployeesByRestaurantRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesByRestaurantRow{}
	for rows.Next() {
		var i ListEmployeesByRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.ShortName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
update employees
set first_name  = coalesce($1, first_name),
    last_name   = coalesce($2, last_name),
    middle_name = coalesce($3, middle_name),
    short_name  = coalesce($4, short_name),
    updated_at  = now()
where id = $5
returning id, first_name, last_name, middle_name, short_name, created_at, updated_at
`

type UpdateEmployeeParams struct {
	FirstName  *string   `json:"first_name"`
	LastName   *string   `json:"last_name"`
	MiddleName *string   `json:"middle_name"`
	ShortName  *string   `json:"short_name"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.ShortName,
		arg.ID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.ShortName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
