// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favourites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addFavourite = `-- name: AddFavourite :exec
insert into favourites (user_id, order_recipe_id)
values ($1, $2)
on conflict do nothing
`

type AddFavouriteParams struct {
	UserID        uuid.UUID `json:"user_id"`
	OrderRecipeID uuid.UUID `json:"order_recipe_id"`
}

func (q *Queries) AddFavourite(ctx context.Context, arg AddFavouriteParams) error {
	_, err := q.db.Exec(ctx, addFavourite, arg.UserID, arg.OrderRecipeID)
	return err
}

const listFavourites = `-- name: ListFavourites :many
select
    f.order_recipe_id,
    f.liked_at,
    orr.recipe_id,
    orr.employee_id,
    r.name        as recipe_name,
    r.strength    as recipe_strength,
    r.is_secret   as recipe_is_secret,
    e.first_name,
    e.last_name,
    e.middle_name,
    e.short_name,
    o.restaurant_id,
    rest.name     as restaurant_name,
    fb.score      as my_score,
    fb.review     as my_review
from favourites f
join order_recipes orr on orr.id = f.order_recipe_id
join recipes r        on r.id = orr.recipe_id
join employees e      on e.id = orr.employee_id
join orders o         on o.id = orr.order_id
join restaurants rest on rest.id = o.restaurant_id
left join order_recipe_feedback fb
       on fb.order_recipe_id = f.order_recipe_id and fb.user_id = f.user_id
where f.user_id = $1
order by f.liked_at desc
`

type ListFavouritesRow struct {
	OrderRecipeID  uuid.UUID `json:"order_recipe_id"`
	LikedAt        time.Time `json:"liked_at"`
	RecipeID       uuid.UUID `json:"recipe_id"`
	EmployeeID     uuid.UUID `json:"employee_id"`
	RecipeName     *string   `json:"recipe_name"`
	RecipeStrength *int32    `json:"recipe_strength"`
	RecipeIsSecret bool      `json:"recipe_is_secret"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	MiddleName     string    `json:"middle_name"`
	ShortName      string    `json:"short_name"`
	RestaurantID   uuid.UUID `json:"restaurant_id"`
	RestaurantName string    `json:"restaurant_name"`
	MyScore        *int32    `json:"my_score"`
	MyReview       *string   `json:"my_review"`
}

func (q *Queries) ListFavourites(ctx context.Context, userID uuid.UUID) ([]ListFavouritesRow, error) {
	rows, err := q.db.Query(ctx, listFavourites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavouritesRow{}
	for rows.Next() {
		var i ListFavouritesRow
		if err := rows.Scan(
			&i.OrderRecipeID,
			&i.LikedAt,
			&i.RecipeID,
			&i.EmployeeID,
			&i.RecipeName,
			&i.RecipeStrength,
			&i.RecipeIsSecret,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.ShortName,
			&i.RestaurantID,
			&i.RestaurantName,
			&i.MyScore,
			&i.MyReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavourite = `-- name: RemoveFavourite :exec
delete from favourites
where user_id = $1 and order_recipe_id = $2
`

type RemoveFavouriteParams struct {
	UserID        uuid.UUID `json:"user_id"`
	OrderRecipeID uuid.UUID `json:"order_recipe_id"`
}

func (q *Queries) RemoveFavourite(ctx context.Context, arg RemoveFavouriteParams) error {
	_, err := q.db.Exec(ctx, removeFavourite, arg.UserID, arg.OrderRecipeID)
	return err
}
