// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listEmployeeRecipeFeedback = `-- name: ListEmployeeRecipeFeedback :many
select
    f.order_recipe_id,
    f.score,
    f.review,
    f.updated_at,
    orr.recipe_id,
    r.name as recipe_name,
    r.strength as recipe_strength
from order_recipe_feedback f
join order_recipes orr on orr.id = f.order_recipe_id
join recipes r         on r.id = orr.recipe_id
where orr.employee_id = $1
  and (f.score is not null or f.review is not null)
order by f.updated_at desc
`

type ListEmployeeRecipeFeedbackRow struct {
	OrderRecipeID  uuid.UUID `json:"order_recipe_id"`
	Score          *int32    `json:"score"`
	Review         *string   `json:"review"`
	UpdatedAt      time.Time `json:"updated_at"`
	RecipeID       uuid.UUID `json:"recipe_id"`
	RecipeName     *string   `json:"recipe_name"`
	RecipeStrength *int32    `json:"recipe_strength"`
}

func (q *Queries) ListEmployeeRecipeFeedback(ctx context.Context, employeeID uuid.UUID) ([]ListEmployeeRecipeFeedbackRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeRecipeFeedback, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeRecipeFeedbackRow{}
	for rows.Next() {
		var i ListEmployeeRecipeFeedbackRow
		if err := rows.Scan(
			&i.OrderRecipeID,
			&i.Score,
			&i.Review,
			&i.UpdatedAt,
			&i.RecipeID,
			&i.RecipeName,
			&i.RecipeStrength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrderRecipeRating = `-- name: UpsertOrderRecipeRating :one
insert into order_recipe_feedback (order_recipe_id, user_id, score)
values ($1, $2, $3)
on conflict (order_recipe_id, user_id)
do update set score = excluded.score, updated_at = now()
returning id, order_recipe_id, user_id, score, review, created_at, updated_at
`

type UpsertOrderRecipeRatingParams struct {
	OrderRecipeID uuid.UUID `json:"order_recipe_id"`
	UserID        uuid.UUID `json:"user_id"`
	Score         *int32    `json:"score"`
}

func (q *Queries) UpsertOrderRecipeRating(ctx context.Context, arg UpsertOrderRecipeRatingParams) (OrderRecipeFeedback, error) {
	row := q.db.QueryRow(ctx, upsertOrderRecipeRating, arg.OrderRecipeID, arg.UserID, arg.Score)
	var i OrderRecipeFeedback
	err := row.Scan(
		&i.ID,
		&i.OrderRecipeID,
		&i.UserID,
		&i.Score,
		&i.Review,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrderRecipeReview = `-- name: UpsertOrderRecipeReview :one
insert into order_recipe_feedback (order_recipe_id, user_id, review)
values ($1, $2, $3)
on conflict (order_recipe_id, user_id)
do update set review = excluded.review, updated_at = now()
returning id, order_recipe_id, user_id, score, review, created_at, updated_at
`

type UpsertOrderRecipeReviewParams struct {
	OrderRecipeID uuid.UUID `json:"order_recipe_id"`
	UserID        uuid.UUID `json:"user_id"`
	Review        *string   `json:"review"`
}

func (q *Queries) UpsertOrderRecipeReview(ctx context.Context, arg UpsertOrderRecipeReviewParams) (OrderRecipeFeedback, error) {
	row := q.db.QueryRow(ctx, upsertOrderRecipeReview, arg.OrderRecipeID, arg.UserID, arg.Review)
	var i OrderRecipeFeedback
	err := row.Scan(
		&i.ID,
		&i.OrderRecipeID,
		&i.UserID,
		&i.Score,
		&i.Review,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
