// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMenuRecipe = `-- name: CreateMenuRecipe :one
insert into menu_recipes
    (restaurant_id, author_employee_id, name, description, strength, price, rating, tags, badge)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge
`

type CreateMenuRecipeParams struct {
	RestaurantID     uuid.UUID `json:"restaurant_id"`
	AuthorEmployeeID uuid.UUID `json:"author_employee_id"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	Strength         int32     `json:"strength"`
	Price            float64   `json:"price"`
	Rating           *float64  `json:"rating"`
	Tags             []string  `json:"tags"`
	Badge            *string   `json:"badge"`
}

func (q *Queries) CreateMenuRecipe(ctx context.Context, arg CreateMenuRecipeParams) (MenuRecipe, error) {
	row := q.db.QueryRow(ctx, createMenuRecipe,
		arg.RestaurantID,
		arg.AuthorEmployeeID,
		arg.Name,
		arg.Description,
		arg.Strength,
		arg.Price,
		arg.Rating,
		arg.Tags,
		arg.Badge,
	)
	var i MenuRecipe
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.AuthorEmployeeID,
		&i.Name,
		&i.Description,
		&i.Strength,
		&i.Price,
		&i.Rating,
		&i.Tags,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
	)
	return i, err
}

const getMenuRecipe = `-- name: GetMenuRecipe :one
select id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge from menu_recipes
where id = $1
`

func (q *Queries) GetMenuRecipe(ctx context.Context, id uuid.UUID) (MenuRecipe, error) {
	row := q.db.QueryRow(ctx, getMenuRecipe, id)
	var i MenuRecipe
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.AuthorEmployeeID,
		&i.Name,
		&i.Description,
		&i.Strength,
		&i.Price,
		&i.Rating,
		&i.Tags,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
	)
	return i, err
}

const listMenuRecipes = `-- name: ListMenuRecipes :many
select id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge from menu_recipes
where restaurant_id = $1 and removed_at is null
order by created_at desc
`

func (q *Queries) ListMenuRecipes(ctx context.Context, restaurantID uuid.UUID) ([]MenuRecipe, error) {
	rows, err := q.db.Query(ctx, listMenuRecipes, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuRecipe{}
	for rows.Next() {
		var i MenuRecipe
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.AuthorEmployeeID,
			&i.Name,
			&i.Description,
			&i.Strength,
			&i.Price,
			&i.Rating,
			&i.Tags,
			&i.RemovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Badge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softRemoveMenuRecipe = `-- name: SoftRemoveMenuRecipe :exec
update menu_recipes
set removed_at = now(), updated_at = now()
where id = $1 and removed_at is null
`

func (q *Queries) SoftRemoveMenuRecipe(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softRemoveMenuRecipe, id)
	return err
}

const updateMenuRecipe = `-- name: UpdateMenuRecipe :one
update menu_recipes
set name        = $2,
    description = $3,
    strength    = $4,
    price       = $5,
    rating      = $6,
    tags        = $7,
    badge       = $8,
    updated_at  = now()
where id = $1 and removed_at is null
returning id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge
`

type UpdateMenuRecipeParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Strength    int32     `json:"strength"`
	Price       float64   `json:"price"`
	Rating      *float64  `json:"rating"`
	Tags        []string  `json:"tags"`
	Badge       *string   `json:"badge"`
}

func (q *Queries) UpdateMenuRecipe(ctx context.Context, arg UpdateMenuRecipeParams) (MenuRecipe, error) {
	row := q.db.QueryRow(ctx, updateMenuRecipe,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Strength,
		arg.Price,
		arg.Rating,
		arg.Tags,
		arg.Badge,
	)
	var i MenuRecipe
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.AuthorEmployeeID,
		&i.Name,
		&i.Description,
		&i.Strength,
		&i.Price,
		&i.Rating,
		&i.Tags,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
	)
	return i, err
}
