// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuRecipe = `-- name: CreateMenuRecipe :one
insert into menu_recipes
    (restaurant_id, author_employee_id, name, description, strength, price, rating, tags, badge,
     kind, category, available, image_slug, components, sort_order)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
     coalesce((select max(sort_order) + 1 from menu_recipes
               where restaurant_id = $1 and removed_at is null), 0))
returning id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge, kind, category, available, sort_order, image_slug, components
`

type CreateMenuRecipeParams struct {
	RestaurantID     uuid.UUID `json:"restaurant_id"`
	AuthorEmployeeID uuid.UUID `json:"author_employee_id"`
	Name             string    `json:"name"`
	Description      string    `json:"description"`
	Strength         int32     `json:"strength"`
	Price            float64   `json:"price"`
	Rating           *float64  `json:"rating"`
	Tags             []string  `json:"tags"`
	Badge            *string   `json:"badge"`
	Kind             string    `json:"kind"`
	Category         string    `json:"category"`
	Available        bool      `json:"available"`
	ImageSlug        *string   `json:"image_slug"`
	Components       []byte    `json:"components"`
}

func (q *Queries) CreateMenuRecipe(ctx context.Context, arg CreateMenuRecipeParams) (MenuRecipe, error) {
	row := q.db.QueryRow(ctx, createMenuRecipe,
		arg.RestaurantID,
		arg.AuthorEmployeeID,
		arg.Name,
		arg.Description,
		arg.Strength,
		arg.Price,
		arg.Rating,
		arg.Tags,
		arg.Badge,
		arg.Kind,
		arg.Category,
		arg.Available,
		arg.ImageSlug,
		arg.Components,
	)
	var i MenuRecipe
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.AuthorEmployeeID,
		&i.Name,
		&i.Description,
		&i.Strength,
		&i.Price,
		&i.Rating,
		&i.Tags,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
		&i.Kind,
		&i.Category,
		&i.Available,
		&i.SortOrder,
		&i.ImageSlug,
		&i.Components,
	)
	return i, err
}

const getMenuRecipe = `-- name: GetMenuRecipe :one
select id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge, kind, category, available, sort_order, image_slug, components from menu_recipes
where id = $1 and removed_at is null
`

func (q *Queries) GetMenuRecipe(ctx context.Context, id uuid.UUID) (MenuRecipe, error) {
	row := q.db.QueryRow(ctx, getMenuRecipe, id)
	var i MenuRecipe
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.AuthorEmployeeID,
		&i.Name,
		&i.Description,
		&i.Strength,
		&i.Price,
		&i.Rating,
		&i.Tags,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
		&i.Kind,
		&i.Category,
		&i.Available,
		&i.SortOrder,
		&i.ImageSlug,
		&i.Components,
	)
	return i, err
}

const listFoodMenu = `-- name: ListFoodMenu :many
select id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge, kind, category, available, sort_order, image_slug, components from menu_recipes
where restaurant_id = $1 and removed_at is null and available and kind = 'kitchen'
order by sort_order, created_at
`

// Guest kitchen-bar menu: available kitchen positions only.
func (q *Queries) ListFoodMenu(ctx context.Context, restaurantID uuid.UUID) ([]MenuRecipe, error) {
	rows, err := q.db.Query(ctx, listFoodMenu, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuRecipe{}
	for rows.Next() {
		var i MenuRecipe
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.AuthorEmployeeID,
			&i.Name,
			&i.Description,
			&i.Strength,
			&i.Price,
			&i.Rating,
			&i.Tags,
			&i.RemovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Badge,
			&i.Kind,
			&i.Category,
			&i.Available,
			&i.SortOrder,
			&i.ImageSlug,
			&i.Components,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuRecipes = `-- name: ListMenuRecipes :many
select id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge, kind, category, available, sort_order, image_slug, components from menu_recipes
where restaurant_id = $1 and removed_at is null and available and kind = 'hookah'
order by sort_order, created_at
`

// Guest hookah menu: available hookah positions only, in admin-defined order.
func (q *Queries) ListMenuRecipes(ctx context.Context, restaurantID uuid.UUID) ([]MenuRecipe, error) {
	rows, err := q.db.Query(ctx, listMenuRecipes, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuRecipe{}
	for rows.Next() {
		var i MenuRecipe
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.AuthorEmployeeID,
			&i.Name,
			&i.Description,
			&i.Strength,
			&i.Price,
			&i.Rating,
			&i.Tags,
			&i.RemovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Badge,
			&i.Kind,
			&i.Category,
			&i.Available,
			&i.SortOrder,
			&i.ImageSlug,
			&i.Components,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuRecipesAdmin = `-- name: ListMenuRecipesAdmin :many
select id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge, kind, category, available, sort_order, image_slug, components from menu_recipes
where restaurant_id = $1 and removed_at is null
order by sort_order, created_at
`

// Admin menu: every non-removed position (incl. unavailable and kitchen).
func (q *Queries) ListMenuRecipesAdmin(ctx context.Context, restaurantID uuid.UUID) ([]MenuRecipe, error) {
	rows, err := q.db.Query(ctx, listMenuRecipesAdmin, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuRecipe{}
	for rows.Next() {
		var i MenuRecipe
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.AuthorEmployeeID,
			&i.Name,
			&i.Description,
			&i.Strength,
			&i.Price,
			&i.Rating,
			&i.Tags,
			&i.RemovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Badge,
			&i.Kind,
			&i.Category,
			&i.Available,
			&i.SortOrder,
			&i.ImageSlug,
			&i.Components,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderMenuRecipes = `-- name: ReorderMenuRecipes :exec
update menu_recipes m
set sort_order = t.ord - 1, updated_at = now()
from unnest($1::uuid[]) with ordinality as t(id, ord)
where m.id = t.id and m.removed_at is null
`

// Bulk-set sort_order from the position of each id in the array (0-based).
func (q *Queries) ReorderMenuRecipes(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, reorderMenuRecipes, ids)
	return err
}

const softRemoveMenuRecipe = `-- name: SoftRemoveMenuRecipe :exec
update menu_recipes
set removed_at = now(), updated_at = now()
where id = $1 and removed_at is null
`

func (q *Queries) SoftRemoveMenuRecipe(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softRemoveMenuRecipe, id)
	return err
}

const updateMenuRecipe = `-- name: UpdateMenuRecipe :one
update menu_recipes
set name        = coalesce($1, name),
    description = coalesce($2, description),
    strength    = coalesce($3, strength),
    price       = coalesce($4, price),
    rating      = coalesce($5, rating),
    tags        = coalesce($6, tags),
    badge       = coalesce($7, badge),
    kind        = coalesce($8, kind),
    category    = coalesce($9, category),
    available   = coalesce($10, available),
    sort_order  = coalesce($11, sort_order),
    image_slug  = coalesce($12, image_slug),
    components  = coalesce($13, components),
    updated_at  = now()
where id = $14 and removed_at is null
returning id, restaurant_id, author_employee_id, name, description, strength, price, rating, tags, removed_at, created_at, updated_at, badge, kind, category, available, sort_order, image_slug, components
`

type UpdateMenuRecipeParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Strength    *int32      `json:"strength"`
	Price       *float64    `json:"price"`
	Rating      *float64    `json:"rating"`
	Tags        []string    `json:"tags"`
	Badge       *string     `json:"badge"`
	Kind        *string     `json:"kind"`
	Category    *string     `json:"category"`
	Available   pgtype.Bool `json:"available"`
	SortOrder   *int32      `json:"sort_order"`
	ImageSlug   *string     `json:"image_slug"`
	Components  []byte      `json:"components"`
	ID          uuid.UUID   `json:"id"`
}

// Partial update: only fields passed as non-null are changed (coalesce pattern,
// same convention as UpdateEmployee). Nullable fields cannot be cleared to null.
func (q *Queries) UpdateMenuRecipe(ctx context.Context, arg UpdateMenuRecipeParams) (MenuRecipe, error) {
	row := q.db.QueryRow(ctx, updateMenuRecipe,
		arg.Name,
		arg.Description,
		arg.Strength,
		arg.Price,
		arg.Rating,
		arg.Tags,
		arg.Badge,
		arg.Kind,
		arg.Category,
		arg.Available,
		arg.SortOrder,
		arg.ImageSlug,
		arg.Components,
		arg.ID,
	)
	var i MenuRecipe
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.AuthorEmployeeID,
		&i.Name,
		&i.Description,
		&i.Strength,
		&i.Price,
		&i.Rating,
		&i.Tags,
		&i.RemovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
		&i.Kind,
		&i.Category,
		&i.Available,
		&i.SortOrder,
		&i.ImageSlug,
		&i.Components,
	)
	return i, err
}
