// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Call struct {
	ID           uuid.UUID  `json:"id"`
	RestaurantID uuid.UUID  `json:"restaurant_id"`
	TableID      string     `json:"table_id"`
	Type         string     `json:"type"`
	Status       string     `json:"status"`
	CreatedAt    time.Time  `json:"created_at"`
	AckedAt      *time.Time `json:"acked_at"`
	DoneAt       *time.Time `json:"done_at"`
}

type Component struct {
	ID        uuid.UUID `json:"id"`
	RecipeID  uuid.UUID `json:"recipe_id"`
	Brand     string    `json:"brand"`
	Flavour   string    `json:"flavour"`
	Percent   int32     `json:"percent"`
	CreatedAt time.Time `json:"created_at"`
}

type Device struct {
	ID           uuid.UUID `json:"id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Platform     string    `json:"platform"`
	FcmToken     string    `json:"fcm_token"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Employee struct {
	ID         uuid.UUID `json:"id"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	MiddleName string    `json:"middle_name"`
	ShortName  string    `json:"short_name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	Phone      *string   `json:"phone"`
	PhotoSlug  *string   `json:"photo_slug"`
	TipUrl     *string   `json:"tip_url"`
}

type EmployeeRating struct {
	ID         uuid.UUID `json:"id"`
	EmployeeID uuid.UUID `json:"employee_id"`
	UserID     uuid.UUID `json:"user_id"`
	Score      int32     `json:"score"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type EmployeeRestaurant struct {
	EmployeeID   uuid.UUID `json:"employee_id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Rating       *int32    `json:"rating"`
	CreatedAt    time.Time `json:"created_at"`
	Position     *string   `json:"position"`
	Status       string    `json:"status"`
}

type EmployeeSchedule struct {
	ID           uuid.UUID `json:"id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	WorkDate     time.Time `json:"work_date"`
	CreatedAt    time.Time `json:"created_at"`
}

type Favourite struct {
	UserID        uuid.UUID `json:"user_id"`
	OrderRecipeID uuid.UUID `json:"order_recipe_id"`
	LikedAt       time.Time `json:"liked_at"`
}

type MenuRecipe struct {
	ID               uuid.UUID  `json:"id"`
	RestaurantID     uuid.UUID  `json:"restaurant_id"`
	AuthorEmployeeID uuid.UUID  `json:"author_employee_id"`
	Name             string     `json:"name"`
	Description      string     `json:"description"`
	Strength         int32      `json:"strength"`
	Price            float64    `json:"price"`
	Rating           *float64   `json:"rating"`
	Tags             []string   `json:"tags"`
	RemovedAt        *time.Time `json:"removed_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	Badge            *string    `json:"badge"`
	Kind             string     `json:"kind"`
	Category         string     `json:"category"`
	Available        bool       `json:"available"`
	SortOrder        int32      `json:"sort_order"`
	ImageSlug        *string    `json:"image_slug"`
	Components       []byte     `json:"components"`
}

type OnboardingBrief struct {
	ID        uuid.UUID `json:"id"`
	Venue     string    `json:"venue"`
	City      string    `json:"city"`
	Contact   string    `json:"contact"`
	Phone     string    `json:"phone"`
	Payload   []byte    `json:"payload"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	ID           uuid.UUID  `json:"id"`
	TableID      string     `json:"table_id"`
	RestaurantID uuid.UUID  `json:"restaurant_id"`
	UserID       *uuid.UUID `json:"user_id"`
	CreatedAt    time.Time  `json:"created_at"`
	ClosedAt     *time.Time `json:"closed_at"`
}

type OrderRecipe struct {
	ID         uuid.UUID  `json:"id"`
	OrderID    uuid.UUID  `json:"order_id"`
	RecipeID   uuid.UUID  `json:"recipe_id"`
	EmployeeID uuid.UUID  `json:"employee_id"`
	CreatedAt  time.Time  `json:"created_at"`
	RemovedAt  *time.Time `json:"removed_at"`
}

type OrderRecipeFeedback struct {
	ID            uuid.UUID `json:"id"`
	OrderRecipeID uuid.UUID `json:"order_recipe_id"`
	UserID        uuid.UUID `json:"user_id"`
	Score         *int32    `json:"score"`
	Review        *string   `json:"review"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Recipe struct {
	ID        uuid.UUID `json:"id"`
	Name      *string   `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	Strength  *int32    `json:"strength"`
	IsSecret  bool      `json:"is_secret"`
}

type Reservation struct {
	ID           uuid.UUID `json:"id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	GuestName    string    `json:"guest_name"`
	Phone        string    `json:"phone"`
	ResDate      time.Time `json:"res_date"`
	StartTime    string    `json:"start_time"`
	EndTime      string    `json:"end_time"`
	TableID      *string   `json:"table_id"`
	Guests       int32     `json:"guests"`
	Zone         *string   `json:"zone"`
	Status       string    `json:"status"`
	Note         *string   `json:"note"`
	CreatedAt    time.Time `json:"created_at"`
}

type Restaurant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Code      string    `json:"code"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Shift struct {
	ID           uuid.UUID `json:"id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	ShiftDate    time.Time `json:"shift_date"`
	CreatedAt    time.Time `json:"created_at"`
}

type TableAssignment struct {
	ID           uuid.UUID `json:"id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	TableID      string    `json:"table_id"`
	OrderID      uuid.UUID `json:"order_id"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID `json:"id"`
	PhoneNumber string    `json:"phone_number"`
	Gender      *string   `json:"gender"`
	CreatedAt   time.Time `json:"created_at"`
}

type VenueTable struct {
	ID           uuid.UUID  `json:"id"`
	RestaurantID uuid.UUID  `json:"restaurant_id"`
	Label        string     `json:"label"`
	X            float64    `json:"x"`
	Y            float64    `json:"y"`
	Seats        int32      `json:"seats"`
	Shape        string     `json:"shape"`
	ZoneID       *uuid.UUID `json:"zone_id"`
	SortOrder    int32      `json:"sort_order"`
	CreatedAt    time.Time  `json:"created_at"`
}

type Zone struct {
	ID           uuid.UUID `json:"id"`
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Name         string    `json:"name"`
	SortOrder    int32     `json:"sort_order"`
	CreatedAt    time.Time `json:"created_at"`
}
