// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBrief = `-- name: CreateBrief :one
insert into onboarding_briefs (venue, city, contact, phone, payload)
values ($1, $2, $3, $4, $5)
returning id, venue, city, contact, phone, payload, status, created_at
`

type CreateBriefParams struct {
	Venue   string `json:"venue"`
	City    string `json:"city"`
	Contact string `json:"contact"`
	Phone   string `json:"phone"`
	Payload []byte `json:"payload"`
}

// Store a filled onboarding brief. payload is the full form answers as JSON.
func (q *Queries) CreateBrief(ctx context.Context, arg CreateBriefParams) (OnboardingBrief, error) {
	row := q.db.QueryRow(ctx, createBrief,
		arg.Venue,
		arg.City,
		arg.Contact,
		arg.Phone,
		arg.Payload,
	)
	var i OnboardingBrief
	err := row.Scan(
		&i.ID,
		&i.Venue,
		&i.City,
		&i.Contact,
		&i.Phone,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBrief = `-- name: GetBrief :one
select id, venue, city, contact, phone, payload, status, created_at from onboarding_briefs where id = $1
`

func (q *Queries) GetBrief(ctx context.Context, id uuid.UUID) (OnboardingBrief, error) {
	row := q.db.QueryRow(ctx, getBrief, id)
	var i OnboardingBrief
	err := row.Scan(
		&i.ID,
		&i.Venue,
		&i.City,
		&i.Contact,
		&i.Phone,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listBriefs = `-- name: ListBriefs :many
select id, venue, city, contact, phone, payload, status, created_at from onboarding_briefs
order by created_at desc
limit 200
`

// Newest briefs first (admin inbox).
func (q *Queries) ListBriefs(ctx context.Context) ([]OnboardingBrief, error) {
	rows, err := q.db.Query(ctx, listBriefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnboardingBrief{}
	for rows.Next() {
		var i OnboardingBrief
		if err := rows.Scan(
			&i.ID,
			&i.Venue,
			&i.City,
			&i.Contact,
			&i.Phone,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
