// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachRecipe = `-- name: AttachRecipe :one
insert into order_recipes (order_id, recipe_id, employee_id)
values ($1, $2, $3)
returning id, order_id, recipe_id, employee_id, created_at, removed_at
`

type AttachRecipeParams struct {
	OrderID    uuid.UUID `json:"order_id"`
	RecipeID   uuid.UUID `json:"recipe_id"`
	EmployeeID uuid.UUID `json:"employee_id"`
}

func (q *Queries) AttachRecipe(ctx context.Context, arg AttachRecipeParams) (OrderRecipe, error) {
	row := q.db.QueryRow(ctx, attachRecipe, arg.OrderID, arg.RecipeID, arg.EmployeeID)
	var i OrderRecipe
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RecipeID,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const closeOrder = `-- name: CloseOrder :one
update orders
set closed_at = now()
where id = $1 and closed_at is null
returning id, table_id, restaurant_id, user_id, created_at, closed_at
`

func (q *Queries) CloseOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, closeOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.RestaurantID,
		&i.UserID,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
insert into orders (table_id, restaurant_id, user_id)
values ($1, $2, $3)
returning id, table_id, restaurant_id, user_id, created_at, closed_at
`

type CreateOrderParams struct {
	TableID      string     `json:"table_id"`
	RestaurantID uuid.UUID  `json:"restaurant_id"`
	UserID       *uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.TableID, arg.RestaurantID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.RestaurantID,
		&i.UserID,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createTableAssignment = `-- name: CreateTableAssignment :one
insert into table_assignments (restaurant_id, table_id, order_id)
values ($1, $2, $3)
returning id, restaurant_id, table_id, order_id, updated_at
`

type CreateTableAssignmentParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	TableID      string    `json:"table_id"`
	OrderID      uuid.UUID `json:"order_id"`
}

func (q *Queries) CreateTableAssignment(ctx context.Context, arg CreateTableAssignmentParams) (TableAssignment, error) {
	row := q.db.QueryRow(ctx, createTableAssignment, arg.RestaurantID, arg.TableID, arg.OrderID)
	var i TableAssignment
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableID,
		&i.OrderID,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTableAssignmentByOrder = `-- name: DeleteTableAssignmentByOrder :exec
delete from table_assignments
where order_id = $1
`

func (q *Queries) DeleteTableAssignmentByOrder(ctx context.Context, orderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTableAssignmentByOrder, orderID)
	return err
}

const getOrder = `-- name: GetOrder :one
select id, table_id, restaurant_id, user_id, created_at, closed_at from orders
where id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.RestaurantID,
		&i.UserID,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getTableAssignment = `-- name: GetTableAssignment :one
select id, restaurant_id, table_id, order_id, updated_at from table_assignments
where restaurant_id = $1 and table_id = $2
`

type GetTableAssignmentParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	TableID      string    `json:"table_id"`
}

func (q *Queries) GetTableAssignment(ctx context.Context, arg GetTableAssignmentParams) (TableAssignment, error) {
	row := q.db.QueryRow(ctx, getTableAssignment, arg.RestaurantID, arg.TableID)
	var i TableAssignment
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.TableID,
		&i.OrderID,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOrderRecipes = `-- name: ListActiveOrderRecipes :many
select
    orr.id as order_recipe_id,
    orr.recipe_id,
    orr.employee_id,
    r.name as recipe_name,
    r.strength as recipe_strength,
    r.is_secret as recipe_is_secret,
    e.first_name,
    e.last_name,
    e.middle_name,
    e.short_name,
    orr.created_at
from order_recipes orr
join recipes r   on r.id = orr.recipe_id
join employees e on e.id = orr.employee_id
where orr.order_id = $1 and orr.removed_at is null
order by orr.created_at
`

type ListActiveOrderRecipesRow struct {
	OrderRecipeID  uuid.UUID `json:"order_recipe_id"`
	RecipeID       uuid.UUID `json:"recipe_id"`
	EmployeeID     uuid.UUID `json:"employee_id"`
	RecipeName     *string   `json:"recipe_name"`
	RecipeStrength *int32    `json:"recipe_strength"`
	RecipeIsSecret bool      `json:"recipe_is_secret"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	MiddleName     string    `json:"middle_name"`
	ShortName      string    `json:"short_name"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ListActiveOrderRecipes(ctx context.Context, orderID uuid.UUID) ([]ListActiveOrderRecipesRow, error) {
	rows, err := q.db.Query(ctx, listActiveOrderRecipes, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOrderRecipesRow{}
	for rows.Next() {
		var i ListActiveOrderRecipesRow
		if err := rows.Scan(
			&i.OrderRecipeID,
			&i.RecipeID,
			&i.EmployeeID,
			&i.RecipeName,
			&i.RecipeStrength,
			&i.RecipeIsSecret,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softRemoveOrderRecipe = `-- name: SoftRemoveOrderRecipe :one
update order_recipes
set removed_at = now()
where id = $1 and order_id = $2 and removed_at is null
returning id, order_id, recipe_id, employee_id, created_at, removed_at
`

type SoftRemoveOrderRecipeParams struct {
	ID      uuid.UUID `json:"id"`
	OrderID uuid.UUID `json:"order_id"`
}

func (q *Queries) SoftRemoveOrderRecipe(ctx context.Context, arg SoftRemoveOrderRecipeParams) (OrderRecipe, error) {
	row := q.db.QueryRow(ctx, softRemoveOrderRecipe, arg.ID, arg.OrderID)
	var i OrderRecipe
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.RecipeID,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}
