// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddFavourite(ctx context.Context, arg AddFavouriteParams) error
	AddShiftToday(ctx context.Context, arg AddShiftTodayParams) error
	AttachRecipe(ctx context.Context, arg AttachRecipeParams) (OrderRecipe, error)
	CloseOrder(ctx context.Context, id uuid.UUID) (Order, error)
	CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateMenuRecipe(ctx context.Context, arg CreateMenuRecipeParams) (MenuRecipe, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error)
	CreateTableAssignment(ctx context.Context, arg CreateTableAssignmentParams) (TableAssignment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteShiftsToday(ctx context.Context, restaurantID uuid.UUID) error
	DeleteTableAssignmentByOrder(ctx context.Context, orderID uuid.UUID) error
	GetEmployeeRatingAgg(ctx context.Context, employeeID uuid.UUID) (GetEmployeeRatingAggRow, error)
	GetEmployeesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Employee, error)
	GetMenuRecipe(ctx context.Context, id uuid.UUID) (MenuRecipe, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetRecipesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Recipe, error)
	GetRestaurantByCode(ctx context.Context, code string) (Restaurant, error)
	GetTableAssignment(ctx context.Context, arg GetTableAssignmentParams) (TableAssignment, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phoneNumber string) (User, error)
	LinkEmployeeRestaurant(ctx context.Context, arg LinkEmployeeRestaurantParams) error
	ListActiveOrderRecipes(ctx context.Context, orderID uuid.UUID) ([]ListActiveOrderRecipesRow, error)
	ListComponentsByRecipeID(ctx context.Context, recipeID uuid.UUID) ([]Component, error)
	ListComponentsByRecipeIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Component, error)
	ListEmployeeRatings(ctx context.Context, employeeID uuid.UUID) ([]ListEmployeeRatingsRow, error)
	ListEmployeeRecipeFeedback(ctx context.Context, employeeID uuid.UUID) ([]ListEmployeeRecipeFeedbackRow, error)
	ListEmployeesByRestaurant(ctx context.Context, restaurantID uuid.UUID) ([]ListEmployeesByRestaurantRow, error)
	ListFavourites(ctx context.Context, userID uuid.UUID) ([]ListFavouritesRow, error)
	ListMenuRecipes(ctx context.Context, restaurantID uuid.UUID) ([]MenuRecipe, error)
	ListShiftToday(ctx context.Context, restaurantID uuid.UUID) ([]ListShiftTodayRow, error)
	RemoveFavourite(ctx context.Context, arg RemoveFavouriteParams) error
	SoftRemoveMenuRecipe(ctx context.Context, id uuid.UUID) error
	SoftRemoveOrderRecipe(ctx context.Context, arg SoftRemoveOrderRecipeParams) (OrderRecipe, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	UpdateMenuRecipe(ctx context.Context, arg UpdateMenuRecipeParams) (MenuRecipe, error)
	UpsertEmployeeRating(ctx context.Context, arg UpsertEmployeeRatingParams) (EmployeeRating, error)
	UpsertOrderRecipeRating(ctx context.Context, arg UpsertOrderRecipeRatingParams) (OrderRecipeFeedback, error)
	UpsertOrderRecipeReview(ctx context.Context, arg UpsertOrderRecipeReviewParams) (OrderRecipeFeedback, error)
}

var _ Querier = (*Queries)(nil)
