// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getEmployeeRatingAgg = `-- name: GetEmployeeRatingAgg :one
select
    coalesce(avg(score), 0)::float8 as average,
    count(*)::int as count
from employee_ratings
where employee_id = $1
`

type GetEmployeeRatingAggRow struct {
	Average float64 `json:"average"`
	Count   int32   `json:"count"`
}

func (q *Queries) GetEmployeeRatingAgg(ctx context.Context, employeeID uuid.UUID) (GetEmployeeRatingAggRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeRatingAgg, employeeID)
	var i GetEmployeeRatingAggRow
	err := row.Scan(&i.Average, &i.Count)
	return i, err
}

const listEmployeeRatings = `-- name: ListEmployeeRatings :many
select score, updated_at, user_id
from employee_ratings
where employee_id = $1
order by updated_at desc
`

type ListEmployeeRatingsRow struct {
	Score     int32     `json:"score"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListEmployeeRatings(ctx context.Context, employeeID uuid.UUID) ([]ListEmployeeRatingsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeRatings, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeRatingsRow{}
	for rows.Next() {
		var i ListEmployeeRatingsRow
		if err := rows.Scan(&i.Score, &i.UpdatedAt, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmployeeRating = `-- name: UpsertEmployeeRating :one
insert into employee_ratings (employee_id, user_id, score)
values ($1, $2, $3)
on conflict (employee_id, user_id)
do update set score = excluded.score, updated_at = now()
returning id, employee_id, user_id, score, created_at, updated_at
`

type UpsertEmployeeRatingParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	UserID     uuid.UUID `json:"user_id"`
	Score      int32     `json:"score"`
}

func (q *Queries) UpsertEmployeeRating(ctx context.Context, arg UpsertEmployeeRatingParams) (EmployeeRating, error) {
	row := q.db.QueryRow(ctx, upsertEmployeeRating, arg.EmployeeID, arg.UserID, arg.Score)
	var i EmployeeRating
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.UserID,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
