// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createComponent = `-- name: CreateComponent :one
insert into components (recipe_id, brand, flavour, percent)
values ($1, $2, $3, $4)
returning id, recipe_id, brand, flavour, percent, created_at
`

type CreateComponentParams struct {
	RecipeID uuid.UUID `json:"recipe_id"`
	Brand    string    `json:"brand"`
	Flavour  string    `json:"flavour"`
	Percent  int32     `json:"percent"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.RecipeID,
		arg.Brand,
		arg.Flavour,
		arg.Percent,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Brand,
		&i.Flavour,
		&i.Percent,
		&i.CreatedAt,
	)
	return i, err
}

const createRecipe = `-- name: CreateRecipe :one
insert into recipes (name, strength, is_secret)
values ($1, $2, $3)
returning id, name, created_at, strength, is_secret
`

type CreateRecipeParams struct {
	Name     *string `json:"name"`
	Strength *int32  `json:"strength"`
	IsSecret bool    `json:"is_secret"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe, arg.Name, arg.Strength, arg.IsSecret)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Strength,
		&i.IsSecret,
	)
	return i, err
}

const getRecipesByIDs = `-- name: GetRecipesByIDs :many
select id, name, created_at, strength, is_secret from recipes
where id = any($1::uuid[])
`

func (q *Queries) GetRecipesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, getRecipesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Strength,
			&i.IsSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsByRecipeIDs = `-- name: ListComponentsByRecipeIDs :many
select id, recipe_id, brand, flavour, percent, created_at from components
where recipe_id = any($1::uuid[])
order by recipe_id, created_at
`

func (q *Queries) ListComponentsByRecipeIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponentsByRecipeIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Brand,
			&i.Flavour,
			&i.Percent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
