// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
insert into reservations
    (restaurant_id, guest_name, phone, res_date, start_time, end_time,
     table_id, guests, zone, status, note)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
returning id, restaurant_id, guest_name, phone, res_date, start_time, end_time, table_id, guests, zone, status, note, created_at
`

type CreateReservationParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	GuestName    string    `json:"guest_name"`
	Phone        string    `json:"phone"`
	ResDate      time.Time `json:"res_date"`
	StartTime    string    `json:"start_time"`
	EndTime      string    `json:"end_time"`
	TableID      *string   `json:"table_id"`
	Guests       int32     `json:"guests"`
	Zone         *string   `json:"zone"`
	Status       string    `json:"status"`
	Note         *string   `json:"note"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.RestaurantID,
		arg.GuestName,
		arg.Phone,
		arg.ResDate,
		arg.StartTime,
		arg.EndTime,
		arg.TableID,
		arg.Guests,
		arg.Zone,
		arg.Status,
		arg.Note,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.GuestName,
		&i.Phone,
		&i.ResDate,
		&i.StartTime,
		&i.EndTime,
		&i.TableID,
		&i.Guests,
		&i.Zone,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReservation = `-- name: DeleteReservation :exec
delete from reservations where id = $1
`

func (q *Queries) DeleteReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReservation, id)
	return err
}

const listReservations = `-- name: ListReservations :many
select id, restaurant_id, guest_name, phone, res_date, start_time, end_time, table_id, guests, zone, status, note, created_at from reservations
where restaurant_id = $1
  and ($2::date is null or res_date = $2::date)
order by res_date, start_time
`

type ListReservationsParams struct {
	RestaurantID uuid.UUID  `json:"restaurant_id"`
	ResDate      *time.Time `json:"res_date"`
}

// All reservations of a restaurant, optionally filtered to a single day.
// Sorted by date then start time (matches the admin "Брони" list).
func (q *Queries) ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservations, arg.RestaurantID, arg.ResDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.GuestName,
			&i.Phone,
			&i.ResDate,
			&i.StartTime,
			&i.EndTime,
			&i.TableID,
			&i.Guests,
			&i.Zone,
			&i.Status,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReservationStatus = `-- name: SetReservationStatus :exec
update reservations
set status = $2
where id = $1
`

type SetReservationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) error {
	_, err := q.db.Exec(ctx, setReservationStatus, arg.ID, arg.Status)
	return err
}

const updateReservation = `-- name: UpdateReservation :one
update reservations
set guest_name = coalesce($1, guest_name),
    phone      = coalesce($2, phone),
    res_date   = coalesce($3, res_date),
    start_time = coalesce($4, start_time),
    end_time   = coalesce($5, end_time),
    table_id   = coalesce($6, table_id),
    guests     = coalesce($7, guests),
    zone       = coalesce($8, zone),
    status     = coalesce($9, status),
    note       = coalesce($10, note)
where id = $11
returning id, restaurant_id, guest_name, phone, res_date, start_time, end_time, table_id, guests, zone, status, note, created_at
`

type UpdateReservationParams struct {
	GuestName *string    `json:"guest_name"`
	Phone     *string    `json:"phone"`
	ResDate   *time.Time `json:"res_date"`
	StartTime *string    `json:"start_time"`
	EndTime   *string    `json:"end_time"`
	TableID   *string    `json:"table_id"`
	Guests    *int32     `json:"guests"`
	Zone      *string    `json:"zone"`
	Status    *string    `json:"status"`
	Note      *string    `json:"note"`
	ID        uuid.UUID  `json:"id"`
}

// Partial update: only fields passed as non-null are changed (coalesce pattern,
// same convention as UpdateMenuRecipe). Nullable fields cannot be cleared to null.
func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservation,
		arg.GuestName,
		arg.Phone,
		arg.ResDate,
		arg.StartTime,
		arg.EndTime,
		arg.TableID,
		arg.Guests,
		arg.Zone,
		arg.Status,
		arg.Note,
		arg.ID,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.GuestName,
		&i.Phone,
		&i.ResDate,
		&i.StartTime,
		&i.EndTime,
		&i.TableID,
		&i.Guests,
		&i.Zone,
		&i.Status,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
