// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addSchedule = `-- name: AddSchedule :exec
insert into employee_schedule (restaurant_id, employee_id, work_date)
values ($1, $2, $3)
on conflict (restaurant_id, employee_id, work_date) do nothing
`

type AddScheduleParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	WorkDate     time.Time `json:"work_date"`
}

// Mark a master as working on a given calendar day at a venue. Idempotent.
func (q *Queries) AddSchedule(ctx context.Context, arg AddScheduleParams) error {
	_, err := q.db.Exec(ctx, addSchedule, arg.RestaurantID, arg.EmployeeID, arg.WorkDate)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
delete from employee_schedule
where restaurant_id = $1 and employee_id = $2 and work_date = $3
`

type DeleteScheduleParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	WorkDate     time.Time `json:"work_date"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteSchedule, arg.RestaurantID, arg.EmployeeID, arg.WorkDate)
	return err
}

const listScheduleRange = `-- name: ListScheduleRange :many
select
    sch.employee_id,
    e.short_name,
    coalesce(er.position, '')::text as position,
    sch.work_date
from employee_schedule sch
join employees e on e.id = sch.employee_id
left join employee_restaurants er
    on er.employee_id = sch.employee_id
   and er.restaurant_id = sch.restaurant_id
where sch.restaurant_id = $1
  and sch.work_date between $2 and $3
order by e.last_name, e.first_name, sch.work_date
`

type ListScheduleRangeParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	FromDate     time.Time `json:"from_date"`
	ToDate       time.Time `json:"to_date"`
}

type ListScheduleRangeRow struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	ShortName  string    `json:"short_name"`
	Position   string    `json:"position"`
	WorkDate   time.Time `json:"work_date"`
}

// Every scheduled (master, day) inside [from, to] for a venue. Only masters
// that have at least one day in range appear; the handler folds the rows into
// one ScheduleRow per master with a date -> true map.
func (q *Queries) ListScheduleRange(ctx context.Context, arg ListScheduleRangeParams) ([]ListScheduleRangeRow, error) {
	rows, err := q.db.Query(ctx, listScheduleRange, arg.RestaurantID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRangeRow{}
	for rows.Next() {
		var i ListScheduleRangeRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.ShortName,
			&i.Position,
			&i.WorkDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
