// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shifts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addShiftToday = `-- name: AddShiftToday :exec
insert into shifts (restaurant_id, employee_id)
values ($1, $2)
on conflict (restaurant_id, employee_id, shift_date) do nothing
`

type AddShiftTodayParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
}

func (q *Queries) AddShiftToday(ctx context.Context, arg AddShiftTodayParams) error {
	_, err := q.db.Exec(ctx, addShiftToday, arg.RestaurantID, arg.EmployeeID)
	return err
}

const deleteShiftsToday = `-- name: DeleteShiftsToday :exec
delete from shifts
where restaurant_id = $1 and shift_date = current_date
`

func (q *Queries) DeleteShiftsToday(ctx context.Context, restaurantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShiftsToday, restaurantID)
	return err
}

const listShiftToday = `-- name: ListShiftToday :many
select
    e.id,
    e.first_name,
    e.last_name,
    e.middle_name,
    e.short_name,
    empr.position,
    coalesce(avg(er.score), 0)::float8 as rating,
    count(er.id)::int as rating_count
from shifts s
join employees e              on e.id = s.employee_id
left join employee_restaurants empr on empr.employee_id = e.id and empr.restaurant_id = s.restaurant_id
left join employee_ratings er on er.employee_id = e.id
where s.restaurant_id = $1 and s.shift_date = current_date
group by e.id, empr.position
order by e.last_name, e.first_name
`

type ListShiftTodayRow struct {
	ID          uuid.UUID `json:"id"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	MiddleName  string    `json:"middle_name"`
	ShortName   string    `json:"short_name"`
	Position    *string   `json:"position"`
	Rating      float64   `json:"rating"`
	RatingCount int32     `json:"rating_count"`
}

func (q *Queries) ListShiftToday(ctx context.Context, restaurantID uuid.UUID) ([]ListShiftTodayRow, error) {
	rows, err := q.db.Query(ctx, listShiftToday, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShiftTodayRow{}
	for rows.Next() {
		var i ListShiftTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.ShortName,
			&i.Position,
			&i.Rating,
			&i.RatingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
