// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tables.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countTables = `-- name: CountTables :one
select count(*) from venue_tables where restaurant_id = $1
`

func (q *Queries) CountTables(ctx context.Context, restaurantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTables, restaurantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTable = `-- name: CreateTable :one
insert into venue_tables
    (restaurant_id, label, x, y, seats, shape, zone_id, sort_order)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, restaurant_id, label, x, y, seats, shape, zone_id, sort_order, created_at
`

type CreateTableParams struct {
	RestaurantID uuid.UUID  `json:"restaurant_id"`
	Label        string     `json:"label"`
	X            float64    `json:"x"`
	Y            float64    `json:"y"`
	Seats        int32      `json:"seats"`
	Shape        string     `json:"shape"`
	ZoneID       *uuid.UUID `json:"zone_id"`
	SortOrder    int32      `json:"sort_order"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (VenueTable, error) {
	row := q.db.QueryRow(ctx, createTable,
		arg.RestaurantID,
		arg.Label,
		arg.X,
		arg.Y,
		arg.Seats,
		arg.Shape,
		arg.ZoneID,
		arg.SortOrder,
	)
	var i VenueTable
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Label,
		&i.X,
		&i.Y,
		&i.Seats,
		&i.Shape,
		&i.ZoneID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createZone = `-- name: CreateZone :one
insert into zones (restaurant_id, name, sort_order)
values ($1, $2, $3)
returning id, restaurant_id, name, sort_order, created_at
`

type CreateZoneParams struct {
	RestaurantID uuid.UUID `json:"restaurant_id"`
	Name         string    `json:"name"`
	SortOrder    int32     `json:"sort_order"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone, arg.RestaurantID, arg.Name, arg.SortOrder)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTable = `-- name: DeleteTable :exec
delete from venue_tables where id = $1
`

func (q *Queries) DeleteTable(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTable, id)
	return err
}

const getTableByID = `-- name: GetTableByID :one
select id, restaurant_id, label, x, y, seats, shape, zone_id, sort_order, created_at from venue_tables where id = $1
`

func (q *Queries) GetTableByID(ctx context.Context, id uuid.UUID) (VenueTable, error) {
	row := q.db.QueryRow(ctx, getTableByID, id)
	var i VenueTable
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Label,
		&i.X,
		&i.Y,
		&i.Seats,
		&i.Shape,
		&i.ZoneID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listTablesFull = `-- name: ListTablesFull :many
select
    t.id,
    t.restaurant_id,
    t.label,
    t.x,
    t.y,
    t.seats,
    t.shape,
    t.zone_id,
    o.id         as order_id,
    o.created_at as opened_at
from venue_tables t
left join table_assignments ta
    on ta.restaurant_id = t.restaurant_id and ta.table_id = t.label
left join orders o
    on o.id = ta.order_id and o.closed_at is null
where t.restaurant_id = $1
order by t.sort_order, t.label
`

type ListTablesFullRow struct {
	ID           uuid.UUID  `json:"id"`
	RestaurantID uuid.UUID  `json:"restaurant_id"`
	Label        string     `json:"label"`
	X            float64    `json:"x"`
	Y            float64    `json:"y"`
	Seats        int32      `json:"seats"`
	Shape        string     `json:"shape"`
	ZoneID       *uuid.UUID `json:"zone_id"`
	OrderID      *uuid.UUID `json:"order_id"`
	OpenedAt     *time.Time `json:"opened_at"`
}

// Config + live status: left-join the active (open) order via table_assignments
// (linked by string label). order_id/opened_at are null ⇒ the table is free.
func (q *Queries) ListTablesFull(ctx context.Context, restaurantID uuid.UUID) ([]ListTablesFullRow, error) {
	rows, err := q.db.Query(ctx, listTablesFull, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTablesFullRow{}
	for rows.Next() {
		var i ListTablesFullRow
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Label,
			&i.X,
			&i.Y,
			&i.Seats,
			&i.Shape,
			&i.ZoneID,
			&i.OrderID,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZones = `-- name: ListZones :many
select id, name from zones
where restaurant_id = $1
order by sort_order, name
`

type ListZonesRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ListZones(ctx context.Context, restaurantID uuid.UUID) ([]ListZonesRow, error) {
	rows, err := q.db.Query(ctx, listZones, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZonesRow{}
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTable = `-- name: MoveTable :exec
update venue_tables set x = $2, y = $3 where id = $1
`

type MoveTableParams struct {
	ID uuid.UUID `json:"id"`
	X  float64   `json:"x"`
	Y  float64   `json:"y"`
}

func (q *Queries) MoveTable(ctx context.Context, arg MoveTableParams) error {
	_, err := q.db.Exec(ctx, moveTable, arg.ID, arg.X, arg.Y)
	return err
}

const updateTable = `-- name: UpdateTable :one
update venue_tables
set label   = coalesce($1, label),
    x       = coalesce($2, x),
    y       = coalesce($3, y),
    seats   = coalesce($4, seats),
    shape   = coalesce($5, shape),
    zone_id = coalesce($6, zone_id)
where id = $7
returning id, restaurant_id, label, x, y, seats, shape, zone_id, sort_order, created_at
`

type UpdateTableParams struct {
	Label  *string    `json:"label"`
	X      *float64   `json:"x"`
	Y      *float64   `json:"y"`
	Seats  *int32     `json:"seats"`
	Shape  *string    `json:"shape"`
	ZoneID *uuid.UUID `json:"zone_id"`
	ID     uuid.UUID  `json:"id"`
}

// Partial update: only fields passed as non-null change (coalesce pattern).
func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) (VenueTable, error) {
	row := q.db.QueryRow(ctx, updateTable,
		arg.Label,
		arg.X,
		arg.Y,
		arg.Seats,
		arg.Shape,
		arg.ZoneID,
		arg.ID,
	)
	var i VenueTable
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Label,
		&i.X,
		&i.Y,
		&i.Seats,
		&i.Shape,
		&i.ZoneID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
