// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/employees": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Register an employee at a restaurant (by code)",
                "parameters": [
                    {
                        "description": "Employee data + restaurant code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.RegisterEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/employees.RegisterEmployeeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "unknown code",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/employees/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Get employees by ids (batch)",
                "parameters": [
                    {
                        "description": "Employee ids",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.BatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/employees.EmployeeResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/employees/{id}": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Update an employee (partial)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to change",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.UpdateEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/employees.EmployeeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/employees/{id}/rating": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Get a master's aggregate rating",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/employees.RatingAgg"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/employees/{id}/ratings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "List ratings given to a master (as an employee)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/employees.RatingItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Rate a master (1..5)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User + score",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.RateEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/employees.RatingAgg"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/employees/{id}/recipe-feedback": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Reviews \u0026 scores on a master's recipes (with components)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/employees.RecipeFeedbackItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/employees/{id}/restaurants": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "employees"
                ],
                "summary": "Attach an employee to another restaurant (by code)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Restaurant code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.AttachRestaurantRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/health.Status"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/menu": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "Create a menu recipe",
                "parameters": [
                    {
                        "description": "Menu recipe",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu.CreateMenuRecipeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/menu.MenuRecipeView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/menu/list": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "List a restaurant's menu recipes",
                "parameters": [
                    {
                        "description": "Restaurant id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu.ListMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/menu.MenuRecipeView"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/menu/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "Remove a menu recipe (soft)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Menu recipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "Edit a menu recipe (full replace of editable fields)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Menu recipe ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New values",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu.MenuRecipeInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/menu.MenuRecipeView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/order-recipes/{orderRecipeId}/rating": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Rate an order recipe (1..5)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OrderRecipe ID",
                        "name": "orderRecipeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User + score",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orders.RateOrderRecipeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/orders.FeedbackView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/order-recipes/{orderRecipeId}/review": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Leave a text review on an order recipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OrderRecipe ID",
                        "name": "orderRecipeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User + review",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orders.ReviewOrderRecipeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/orders.FeedbackView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/orders/open": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Open a table order (get-or-create, idempotent)",
                "parameters": [
                    {
                        "description": "Restaurant + table",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orders.OpenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "existing order",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/orders.OrderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "201": {
                        "description": "new order",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/orders.OrderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/orders/{id}/close": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Reset table (delete TableAssignment + set closed_at)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/orders.OrderResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/orders/{id}/recipes": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Attach a recipe to an order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Recipe + author",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orders.AttachRecipeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/db.OrderRecipe"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    },
                    "409": {
                        "description": "order is closed",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/orders/{id}/recipes/{orderRecipeId}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Remove/replace a recipe on an order (soft, removed_at)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OrderRecipe ID",
                        "name": "orderRecipeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/recipes": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Create a recipe with components (must sum to 100%)",
                "parameters": [
                    {
                        "description": "Recipe + components",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipes.CreateRecipeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/recipes.RecipeView"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "validation (e.g. percent != 100)",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/recipes/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "Get recipes by ids (batch), components included",
                "parameters": [
                    {
                        "description": "Recipe ids",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipes.BatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/recipes.RecipeView"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/restaurants": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurants"
                ],
                "summary": "Create a restaurant and get its code",
                "parameters": [
                    {
                        "description": "Restaurant name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.CreateRestaurantRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/employees.RestaurantResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/restaurants/employees": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurants"
                ],
                "summary": "List restaurant employees by code (for login)",
                "parameters": [
                    {
                        "description": "Restaurant code",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.ListByCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/employees.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/restaurants/shift": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurants"
                ],
                "summary": "Set today's masters on shift (by restaurant code)",
                "parameters": [
                    {
                        "description": "Code + employee ids",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/employees.SetShiftRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/employees.ShiftMaster"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/restaurants/{restaurantId}/shift": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "restaurants"
                ],
                "summary": "Today's masters on shift in a restaurant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Restaurant ID",
                        "name": "restaurantId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/employees.ShiftMaster"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a guest",
                "parameters": [
                    {
                        "description": "Guest data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/users.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get guest data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/users.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpx.Envelope"
                        }
                    }
                }
            }
        },
        "/users/{id}/favourites": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List guest favourites (enriched: restaurant, components, author)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httpx.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/users.FavouriteView"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Add a recipe to favourites",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "OrderRecipe to like",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.AddFavouriteRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/users/{id}/favourites/{orderRecipeId}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Remove a recipe from favourites",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OrderRecipe ID",
                        "name": "orderRecipeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "db.OrderRecipe": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "recipe_id": {
                    "type": "string"
                },
                "removed_at": {
                    "type": "string"
                }
            }
        },
        "employees.AttachRestaurantRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "employees.BatchRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "employees.ComponentView": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "flavour": {
                    "type": "string"
                },
                "percent": {
                    "type": "integer"
                }
            }
        },
        "employees.CreateRestaurantRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Bar One"
                }
            }
        },
        "employees.EmployeeResponse": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "employees.ListByCodeRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "employees.LoginResponse": {
            "type": "object",
            "properties": {
                "employees": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/employees.EmployeeResponse"
                    }
                },
                "restaurant": {
                    "$ref": "#/definitions/employees.RestaurantBrief"
                }
            }
        },
        "employees.RateEmployeeRequest": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer",
                    "example": 5
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "employees.RatingAgg": {
            "type": "object",
            "properties": {
                "average": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "employees.RatingItem": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "employees.RecipeFeedbackItem": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/employees.ComponentView"
                    }
                },
                "orderRecipeId": {
                    "type": "string"
                },
                "recipeId": {
                    "type": "string"
                },
                "recipeName": {
                    "type": "string"
                },
                "review": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "strength": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "employees.RegisterEmployeeRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SECRET123"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "position": {
                    "type": "string",
                    "example": "Старший мастер"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "employees.RegisterEmployeeResponse": {
            "type": "object",
            "properties": {
                "employee": {
                    "$ref": "#/definitions/employees.EmployeeResponse"
                },
                "restaurantId": {
                    "type": "string"
                }
            }
        },
        "employees.RestaurantBrief": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "employees.RestaurantResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "employees.SetShiftRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "employeeIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "employees.ShiftMaster": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "ratingCount": {
                    "type": "integer"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "employees.UpdateEmployeeRequest": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "shortName": {
                    "type": "string"
                }
            }
        },
        "health.Status": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "httpx.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "httpx.Envelope": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/httpx.APIError"
                }
            }
        },
        "menu.CreateMenuRecipeRequest": {
            "type": "object",
            "properties": {
                "authorEmployeeId": {
                    "type": "string"
                },
                "badge": {
                    "type": "string",
                    "example": "ХИТ"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "Negroni"
                },
                "price": {
                    "type": "number",
                    "example": 550
                },
                "rating": {
                    "type": "number",
                    "example": 4.6
                },
                "restaurantId": {
                    "type": "string"
                },
                "strength": {
                    "type": "integer",
                    "example": 7
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "menu.ListMenuRequest": {
            "type": "object",
            "properties": {
                "restaurantId": {
                    "type": "string"
                }
            }
        },
        "menu.MenuRecipeInput": {
            "type": "object",
            "properties": {
                "badge": {
                    "type": "string",
                    "example": "ХИТ"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "Negroni"
                },
                "price": {
                    "type": "number",
                    "example": 550
                },
                "rating": {
                    "type": "number",
                    "example": 4.6
                },
                "strength": {
                    "type": "integer",
                    "example": 7
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "menu.MenuRecipeView": {
            "type": "object",
            "properties": {
                "authorEmployeeId": {
                    "type": "string"
                },
                "badge": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "rating": {
                    "type": "number"
                },
                "restaurantId": {
                    "type": "string"
                },
                "strength": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "orders.AttachRecipeRequest": {
            "type": "object",
            "properties": {
                "employeeId": {
                    "type": "string"
                },
                "recipeId": {
                    "type": "string"
                }
            }
        },
        "orders.ComponentView": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "flavour": {
                    "type": "string"
                },
                "percent": {
                    "type": "integer"
                }
            }
        },
        "orders.FeedbackView": {
            "type": "object",
            "properties": {
                "orderRecipeId": {
                    "type": "string"
                },
                "review": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "orders.OpenRequest": {
            "type": "object",
            "properties": {
                "restaurantId": {
                    "type": "string"
                },
                "tableId": {
                    "type": "string",
                    "example": "12"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "orders.OrderRecipeView": {
            "type": "object",
            "properties": {
                "authorFullName": {
                    "type": "string"
                },
                "authorShortName": {
                    "type": "string"
                },
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orders.ComponentView"
                    }
                },
                "isSecret": {
                    "type": "boolean"
                },
                "orderRecipeId": {
                    "type": "string"
                },
                "recipeId": {
                    "type": "string"
                },
                "recipeName": {
                    "type": "string"
                },
                "strength": {
                    "type": "integer"
                }
            }
        },
        "orders.OrderResponse": {
            "type": "object",
            "properties": {
                "closedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recipes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orders.OrderRecipeView"
                    }
                },
                "restaurantId": {
                    "type": "string"
                },
                "tableId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "orders.RateOrderRecipeRequest": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer",
                    "example": 5
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "orders.ReviewOrderRecipeRequest": {
            "type": "object",
            "properties": {
                "review": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "recipes.BatchRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "recipes.ComponentInput": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "DS"
                },
                "flavour": {
                    "type": "string",
                    "example": "apple"
                },
                "percent": {
                    "type": "integer",
                    "example": 20
                }
            }
        },
        "recipes.ComponentView": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "flavour": {
                    "type": "string"
                },
                "percent": {
                    "type": "integer"
                }
            }
        },
        "recipes.CreateRecipeRequest": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipes.ComponentInput"
                    }
                },
                "isSecret": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "example": "Apple Mix"
                },
                "strength": {
                    "type": "integer",
                    "example": 6
                }
            }
        },
        "recipes.RecipeView": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipes.ComponentView"
                    }
                },
                "id": {
                    "type": "string"
                },
                "isSecret": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "strength": {
                    "type": "integer"
                }
            }
        },
        "users.AddFavouriteRequest": {
            "type": "object",
            "properties": {
                "orderRecipeId": {
                    "type": "string"
                }
            }
        },
        "users.ComponentView": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "flavour": {
                    "type": "string"
                },
                "percent": {
                    "type": "integer"
                }
            }
        },
        "users.FavouriteView": {
            "type": "object",
            "properties": {
                "authorFullName": {
                    "type": "string"
                },
                "authorShortName": {
                    "type": "string"
                },
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/users.ComponentView"
                    }
                },
                "isSecret": {
                    "type": "boolean"
                },
                "likedAt": {
                    "type": "string"
                },
                "myReview": {
                    "type": "string"
                },
                "myScore": {
                    "type": "integer"
                },
                "orderRecipeId": {
                    "type": "string"
                },
                "recipeId": {
                    "type": "string"
                },
                "recipeName": {
                    "type": "string"
                },
                "restaurantId": {
                    "type": "string"
                },
                "restaurantName": {
                    "type": "string"
                },
                "strength": {
                    "type": "integer"
                }
            }
        },
        "users.RegisterRequest": {
            "type": "object",
            "properties": {
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+79991234567"
                }
            }
        },
        "users.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "mixMaster API",
	Description:      "Backend for the mixMaster restaurant ordering / recipes app.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
